    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|ARM64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\ARM64\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>ARM64</PlatformTarget>
    <LangVersion>10</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|ARM64'">
    <OutputPath>bin\ARM64\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>ARM64</PlatformTarget>
    <LangVersion>10</LangVersion>
    <ErrorReport>prompt</ErrorReport>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x64\Debug\</OutputPath>
@@ -69,89 +33,23 @@
    <ErrorReport>prompt</ErrorReport>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\Documents\Assembly\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\..\Documents\Assembly\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-publicized">
      <HintPath>..\..\..\..\Documents\Assembly\Assembly-CSharp-publicized.dll</HintPath>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <HintPath>..\..\..\..\Documents\Assembly\CommandSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.API">
      <HintPath>..\..\..\..\Documents\Assembly\Exiled.API.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.CreditTags">
      <HintPath>..\..\..\..\Documents\Assembly\Exiled.CreditTags.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.CustomItems">
      <HintPath>..\..\..\..\Documents\Assembly\Exiled.CustomItems.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.CustomRoles">
      <HintPath>..\..\..\..\Documents\Assembly\Exiled.CustomRoles.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Events">
      <HintPath>..\..\..\..\Documents\Assembly\Exiled.Events.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Loader">
      <HintPath>..\..\..\..\Documents\Assembly\Exiled.Loader.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Permissions">
      <HintPath>..\..\..\..\Documents\Assembly\Exiled.Permissions.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Updater">
      <HintPath>..\..\..\..\Documents\Assembly\Exiled.Updater.dll</HintPath>
    </Reference>
    <Reference Include="LiteDB">
      <HintPath>..\..\..\..\Documents\Assembly\LiteDB.dll</HintPath>
    </Reference>
    <Reference Include="MapEditorReborn">
      <HintPath>..\..\..\..\Documents\Assembly\MapEditorReborn.dll</HintPath>
    </Reference>
    <Reference Include="Mirror_Publicized">
      <HintPath>..\..\..\..\Documents\Assembly\Mirror_Publicized.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Posix">
      <HintPath>..\..\..\..\Documents\Assembly\Mono.Posix.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\Documents\Assembly\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="SemVer">
      <HintPath>..\..\..\..\Documents\Assembly\SemVer.dll</HintPath>
    </Reference>
    <Reference Include="ShadowMain">
      <HintPath>..\..\..\..\Documents\Assembly\ShadowMain.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\Documents\Assembly\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\..\..\Documents\Assembly\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\..\..\Documents\Assembly\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\Documents\Assembly\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\..\Documents\Assembly\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>
      <ItemGroup>
        <PackageReference Include="EXILED" Version="5.3.2" />
        <PackageReference Include="Lib.Harmony" Version="2.2.2" />
        <PackageReference Include="LiteDB" Version="5.0.12" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.2-beta1" />
        <PackageReference Include="YamlDotNet" Version="11.2.1" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="AdvancedHints">
            <HintPath>..\refs\AdvancedHints.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp-firstpass" HintPath="$(EXILED_References)\Assembly-CSharp-firstpass.dll" Private="false" />
        <Reference Include="Mirror" HintPath="$(EXILED_References)\Mirror-Publicized.dll" Private="false" />
        <Reference Include="UnityEngine.CoreModule" HintPath="$(EXILED_References)\UnityEngine.CoreModule.dll" Private="false" />
        <Reference Include="UnityEngine.PhysicsModule" HintPath="$(EXILED_References)\UnityEngine.PhysicsModule.dll" Private="false" />
    </ItemGroup>
  <ItemGroup>
    <Compile Include="Commands\Balance.cs" />
    <Compile Include="Commands\AddMoney.cs" />
@@ -173,4 +71,4 @@
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
</Project>
